title: "부자들의 경제철학"
description: "富者의 思考로 바라보는 富의 原理 — 부자들이 말하지 않는 돈의 철학"
baseurl: "/Wealthy-Mindset"
url: "https://digiahn.github.io"
author: "DigiAHN"
email: ""
lang: ko

# YouTube Channel
youtube_channel: "https://www.youtube.com/channel/UCFAWKsm-3cUKvwSoph9vP0g"
youtube_name: "디지안 월드"

# Related Sites
naver_blog: "https://blog.naver.com/argon"
portfolio_site: "https://digiahn.github.io"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
